# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DevTool < Formula
  desc ""
  homepage "https://github.com/plentymarkets/homebrew-plentytools"
  version "0.0.22"

  depends_on "jq"
  depends_on "mkcert"
  depends_on "gh"
  depends_on "awscli"
  depends_on "mutagen-io/mutagen/mutagen"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "http://brew-proxy.114.plenty.rocks/dev-tool/v0.0.22/dev-tool_0.0.22_Darwin_arm64.tar.gz"
      sha256 "10ac4890c36a59ade3464a4117808381fcefda6b29c9b439fc3134933b1f6c05"

      def install
        bin.install "dev-tool"
      end
    end
    if Hardware::CPU.intel?
      url "http://brew-proxy.114.plenty.rocks/dev-tool/v0.0.22/dev-tool_0.0.22_Darwin_amd64.tar.gz"
      sha256 "985ab448246faf84f436f0f151e883f603cd23b0c8e7388500f025316129f8f9"

      def install
        bin.install "dev-tool"
      end
    end
  end
end
