# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DevTool < Formula
  desc ""
  homepage "https://github.com/plentymarkets/homebrew-plentytools"
  version "0.0.8"

  depends_on "jq"
  depends_on "mkcert"
  depends_on "gh"
  depends_on "awscli"
  depends_on "mutagen-io/mutagen/mutagen"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://homebrew-plenty.s3.eu-central-1.amazonaws.com/dev-tool/v0.0.8/dev-tool_0.0.8_Darwin_arm64.tar.gz"
      sha256 "e30d569fdebb858f08bda0aa9949c6da39b9080e27c9054eaeb0b98138d8315c"

      def install
        bin.install "dev-tool"
      end
    end
    if Hardware::CPU.intel?
      url "https://homebrew-plenty.s3.eu-central-1.amazonaws.com/dev-tool/v0.0.8/dev-tool_0.0.8_Darwin_amd64.tar.gz"
      sha256 "06f07abb04202c15c829a7119142cb1725d130a7c406db7c387151920311b726"

      def install
        bin.install "dev-tool"
      end
    end
  end
end
