# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PlentyPreview < Formula
  desc ""
  homepage "https://github.com/plentymarkets/homebrew-tools"
  version "1.26.7-preview.pr278.21"

  depends_on "gh"
  depends_on "jq"
  depends_on "mkcert"
  depends_on "mutagen-io/mutagen/mutagen" => "0.17.1"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://brew-proxy.eks-114-1.plenty.rocks/plenty/v1.26.7-preview.pr278.21/plenty_1.26.7-preview.pr278.21_Darwin_amd64.tar.gz"
    sha256 "e83a44e52364f2fffa6cf93233417c60c8a24cd11fa44739071083522ad1218f"

    define_method(:install) do
      bin.install "plenty"
      bin.install "scripts/kubectl-plenty"
      bin.install "scripts/plentyctl"
    end
  end
  if Hardware::CPU.arm?
    url "https://brew-proxy.eks-114-1.plenty.rocks/plenty/v1.26.7-preview.pr278.21/plenty_1.26.7-preview.pr278.21_Darwin_arm64.tar.gz"
    sha256 "0d653de5cf737615b2fe7ef339c7d28ddee3e030554122d67ad9dedfd478393e"

    define_method(:install) do
      bin.install "plenty"
      bin.install "scripts/kubectl-plenty"
      bin.install "scripts/plentyctl"
    end
  end
end
