# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PlentyPreview < Formula
  desc ""
  homepage "https://github.com/plentymarkets/homebrew-tools"
  version "1.27.6-preview.pr278.134"

  depends_on "gh"
  depends_on "jq"
  depends_on "mkcert"
  depends_on "mutagen-io/mutagen/mutagen" => "0.17.1"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://brew-proxy.eks-114-1.plenty.rocks/plenty/v1.27.6-preview.pr278.134/plenty_1.27.6-preview.pr278.134_Darwin_amd64.tar.gz"
    sha256 "ca980368afe92349b73f74245b3b42f4b506eee1f6db35c4d8acbec5d169d0f9"

    define_method(:install) do
      bin.install "plenty"
      bin.install "scripts/kubectl-plenty"
      bin.install "scripts/plentyctl"
    end
  end
  if Hardware::CPU.arm?
    url "https://brew-proxy.eks-114-1.plenty.rocks/plenty/v1.27.6-preview.pr278.134/plenty_1.27.6-preview.pr278.134_Darwin_arm64.tar.gz"
    sha256 "4be8cb459eaf8a4ffd3ed916d8bc911d41c4ea6e3474f3844d8d059305539098"

    define_method(:install) do
      bin.install "plenty"
      bin.install "scripts/kubectl-plenty"
      bin.install "scripts/plentyctl"
    end
  end
end
