# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PlentyPreview < Formula
  desc ""
  homepage "https://github.com/plentymarkets/homebrew-tools"
  version "1.27.1-preview.pr278.47"

  depends_on "gh"
  depends_on "jq"
  depends_on "mkcert"
  depends_on "mutagen-io/mutagen/mutagen" => "0.17.1"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://brew-proxy.eks-114-1.plenty.rocks/plenty/v1.27.1-preview.pr278.47/plenty_1.27.1-preview.pr278.47_Darwin_amd64.tar.gz"
    sha256 "91e583264a77197945bd01226f90b9781d0d56915c43a3d9c999b0a978bd1758"

    define_method(:install) do
      bin.install "plenty"
      bin.install "scripts/kubectl-plenty"
      bin.install "scripts/plentyctl"
    end
  end
  if Hardware::CPU.arm?
    url "https://brew-proxy.eks-114-1.plenty.rocks/plenty/v1.27.1-preview.pr278.47/plenty_1.27.1-preview.pr278.47_Darwin_arm64.tar.gz"
    sha256 "c57afe23d849ccbae5c7678379e7076487d03ce0f43f0c9c6ea88ea2312bfe9d"

    define_method(:install) do
      bin.install "plenty"
      bin.install "scripts/kubectl-plenty"
      bin.install "scripts/plentyctl"
    end
  end
end
