# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Plenty < Formula
  desc ""
  homepage "https://github.com/plentymarkets/homebrew-tools"
  version "1.17.1"

  depends_on "gh"
  depends_on "jq"
  depends_on "mkcert"
  depends_on "mutagen-io/mutagen/mutagen" => "0.17.1"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://brew-proxy.eks-114-1.plenty.rocks/plenty/v1.17.1/plenty_1.17.1_Darwin_amd64.tar.gz"
    sha256 "495d72a6bb0b2dabd8921b94702371e472f545d53f50388d9c164a821281e3ea"

    define_method(:install) do
      bin.install "plenty"
      bin.install "scripts/kubectl-plenty"
      bin.install "scripts/plentyctl"
    end
  end
  if Hardware::CPU.arm?
    url "https://brew-proxy.eks-114-1.plenty.rocks/plenty/v1.17.1/plenty_1.17.1_Darwin_arm64.tar.gz"
    sha256 "aaf3421f36686dabdc0736ea6c990dfe5bfc4ed07d24ee0ceff28a2bc76532ca"

    define_method(:install) do
      bin.install "plenty"
      bin.install "scripts/kubectl-plenty"
      bin.install "scripts/plentyctl"
    end
  end
end
